// Generated by gencpp from file lab4_starter/msg_type_position.msg
// DO NOT EDIT!


#ifndef LAB4_STARTER_MESSAGE_MSG_TYPE_POSITION_H
#define LAB4_STARTER_MESSAGE_MSG_TYPE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab4_starter
{
template <class ContainerAllocator>
struct msg_type_position_
{
  typedef msg_type_position_<ContainerAllocator> Type;

  msg_type_position_()
    : position()  {
      position.assign(0.0);
  }
  msg_type_position_(const ContainerAllocator& _alloc)
    : position()  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef boost::array<double, 2>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::lab4_starter::msg_type_position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab4_starter::msg_type_position_<ContainerAllocator> const> ConstPtr;

}; // struct msg_type_position_

typedef ::lab4_starter::msg_type_position_<std::allocator<void> > msg_type_position;

typedef boost::shared_ptr< ::lab4_starter::msg_type_position > msg_type_positionPtr;
typedef boost::shared_ptr< ::lab4_starter::msg_type_position const> msg_type_positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab4_starter::msg_type_position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab4_starter::msg_type_position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab4_starter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'lab4_starter': ['/home/akhil/ros_workspaces/project/src/lab4_starter/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab4_starter::msg_type_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab4_starter::msg_type_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab4_starter::msg_type_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab4_starter::msg_type_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab4_starter::msg_type_position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab4_starter::msg_type_position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab4_starter::msg_type_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f44864fd31f13dff3a84000f39a69268";
  }

  static const char* value(const ::lab4_starter::msg_type_position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf44864fd31f13dffULL;
  static const uint64_t static_value2 = 0x3a84000f39a69268ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab4_starter::msg_type_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab4_starter/msg_type_position";
  }

  static const char* value(const ::lab4_starter::msg_type_position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab4_starter::msg_type_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[2] position\n\
";
  }

  static const char* value(const ::lab4_starter::msg_type_position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab4_starter::msg_type_position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_type_position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab4_starter::msg_type_position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab4_starter::msg_type_position_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB4_STARTER_MESSAGE_MSG_TYPE_POSITION_H
